# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='hostname',
            field=models.CharField(max_length=256),
        ),
    ]
